config/routes.rb
CrumpleAddons::Application.routes.draw do
  resources :markdowns

  resources :music_notation_thoughts

  root :to => 'pages#about'
end

app/models/music_notation_thought.rb
class MusicNotationThought < ActiveRecord::Base
  attr_accessible :body
  def search_text
    # see http://abcnotation.com/abc2mtex/abc.txt
    # TODO: need to handle multiple line text for H
    # and text after % on every line
    %w(A B C D G H I N O S T W Z).map do |f|
      self.body.scan(/^\s*#{f}:(.*)$/).join(' ')
    end.join(' ').gsub(/[^ 0-9A-Za-z_]/,'').squeeze("\s").strip
  end
  def example_body
%(% for info on notation: http://abcnotation.com/abc2mtex/abc.txt
%
% a percent sign denotes the beginning of a comment
%
% T: is for the title
T: Title
%
% M: is the meter
M: 4/4
%
% K: is the key. # for sharp and b for flat
K: Ab
%
% L: is the default note length
L: 1/4
%
% uppercase is the bottom octave: C
% lower case is the top octave: c
% to go down an octave follow the letter with one or more commas: C,,
% to go up an octave follow the letter with one or more apostrophes: C'''
[|:C, C c c' | c' c C C,:|]
%
% to create a longer note follow the letter by a number: c'4
[|:c4 | c3 c | c2 c2:|]
%
% to create shorter notes follow the letter by a forward slash and a number: C/16
% for beams put notes next to each other with no space: C,/16C/16c/16c'/16
[|:c/4c/4c/4c/4 c/2c/2 c/2 c/2 c:|]
%
% to create broken rhythms, like dotted eighth sixteenth notes use greater or less than: c/2<c/2
[|:c/2>c/2 c c/2<c/2 c:|]
)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/music_notation_thoughts_controller.rb
class MusicNotationThoughtsController < ApplicationController
  before_filter :check_platform
  
  def index
    @music_notation_thoughts = MusicNotationThought.all
    respond_to do |format|
      format.html
      format.json  { render :json => @music_notation_thoughts }
      format.xml  { render :xml => @music_notation_thoughts }
    end
  end
  
  def show
    @music_notation_thought = MusicNotationThought.find(params[:id])
    respond_to do |format|
      if @platform == 'crumple'
        format.html {render :layout => false}
      else
        format.html
      end
      format.json  { render :json => music_notation_to_json(@music_notation_thought) }
      format.xml  { render :xml => @music_notation_thought }
    end
  end
  
  def new
    @music_notation_thought = MusicNotationThought.new
    @music_notation_thought.body = @music_notation_thought.example_body

    if @platform == 'crumple'
      render :layout => false
    end
  end
  
  def create
    @music_notation_thought = MusicNotationThought.new(params[:music_notation_thought])
    if @music_notation_thought.save
      flash[:notice] = "Successfully created music notation thought."
      respond_to do |format|
        format.html { redirect_to @music_notation_thought }
        format.xml  { render :xml => @music_notation_thought }
        format.json  { render :json => music_notation_to_json(@music_notation_thought) }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.all  do
          render :text => 'Could not save music notation thought.', :status => :internal_server_error 
        end
      end
    end
  end
  
  def edit
    @music_notation_thought = MusicNotationThought.find(params[:id])
  end
  
  def update
    @music_notation_thought = MusicNotationThought.find(params[:id])
    if @music_notation_thought.update_attributes(params[:music_notation_thought])
      flash[:notice] = "Successfully updated music notation thought."
      respond_to do |format|
        format.html { redirect_to @music_notation_thought }
        format.xml  { render :xml => @music_notation_thought }
        format.json  { render :json => music_notation_to_json(@music_notation_thought) }
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit'}
        format.all  do
          render :text => 'Could not save music notation thought.', :status => :internal_server_error 
        end
      end
    end
  end
  
  def destroy
    @music_notation_thought = MusicNotationThought.find(params[:id])
    @music_notation_thought.destroy
    flash[:notice] = "Successfully destroyed music notation thought."
    respond_to do |format|
      format.html { redirect_to music_notation_thoughts_url }
      format.json  { render :json => nil }
    end
  end
  protected
  def check_platform
    @platform = params[:platform] || ''
  end
  def music_notation_to_json(t)
    t.to_json(:methods => :search_text)
  end
end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/music_notation_thoughts_helper.rb
module MusicNotationThoughtsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  
  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)
  
  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      
      - if show_title?
        %h1= yield(:title)
      
      = yield

app/views/music_notation_thoughts/_form.html.haml
= javascript_include_tag 'music_notation/abc.editor.min', 'music_notation/_form'
= stylesheet_link_tag 'music_notation/application.css'

- if @platform == 'crumple'
  = stylesheet_link_tag 'http://crumpleapp.com/stylesheets/application.css'
- else
  = javascript_include_tag 'jquery.min.js'
:javascript
  window.onload = function() { 
    abc_editor = new ABCEditor('music_notation_thought_body', { canvas_id: 'music_notation_canvas', warnings_id: 'music_notation_warnings'}); 
  }    
- if @platform == 'crumple'
  = text_area :music_notation_thought, :body, :style => 'width:100%', :rows => "10"
  #music_notation_warnings.system-content.gray
  #music_notation_canvas.lil-space-top
- else
  = form_for @music_notation_thought do |f|
    = f.text_area :body, :style => 'width:100%'
    = f.submit

app/views/music_notation_thoughts/edit.html.haml
- title "Edit Music Notation Thought"

= render 'form'

%p
  = link_to "Show", music_notation_thought_path(@music_notation_thought)
  |
  = link_to "View All", music_notation_thoughts_path

app/views/music_notation_thoughts/index.html.haml
- title "Music Notation Thoughts"

%table
  %tr
    %th Body
  - for music_notation_thought in @music_notation_thoughts
    %tr
      %td= music_notation_thought.body
      %td= link_to 'Show', music_notation_thought
      %td= link_to 'Edit', edit_music_notation_thought_path(music_notation_thought)
      %td= link_to 'Destroy', music_notation_thought, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Music Notation Thought", new_music_notation_thought_path

app/views/music_notation_thoughts/new.html.haml
= render 'form'

app/views/music_notation_thoughts/show.html.haml
= javascript_include_tag 'jquery.min.js', 'music_notation/abc.plugin.min', 'music_notation/show'
= stylesheet_link_tag 'music_notation/application.css'
- if @platform == 'crumple'
  = stylesheet_link_tag 'http://crumpleapp.com/stylesheets/application.css'

:javascript
  abc_plugin["show_midi"] = false;
  abc_plugin["hide_abc"] = true;

- if @platform.nil?
  - title "Music Notation Thought"


= 'X: ' + @music_notation_thought.to_param + "\n" + @music_notation_thought.body
- if @platform.nil?
  %p
    = link_to "Edit", edit_music_notation_thought_path(@music_notation_thought)
    |
    = link_to "Destroy", @music_notation_thought, :confirm => 'Are you sure?', :method => :delete
    |
    = link_to "View All", music_notation_thoughts_path

app/views/pages/about.html.haml
This is where the Crumple crew experiments with new stuff, including add-ons.

app/views/pages/music_notation.html.haml
%h1 Music Notation
%p
  If you think in music, this add-on is for you. It is based on the simple and widely used abc notation.
%p
  You can read about abc notation here: 
  = link_to('http://en.wikipedia.org/wiki/Abc_notation', 'http://en.wikipedia.org/wiki/Abc_notation') + '.'
%p
  With this add-on you can quickly jot down melodies, rhythms and harmonies that come to mind.  And like the rest of Crumple you can tag it, stash it in a project and search for it later.
%p
  = image_tag 'music_notation/icon_512.png'